HAR_NUM_FEATURES = 3
HAR_NUM_CLASSES = 6
HAR_MAX_LENGTH = 206

SLEEP_NUM_FEATURES = 1
SLEEP_NUM_CLASSES = 5
SLEEP_MAX_LENGTH = 3000

MIMIC_NUM_FEATURES = 31
MIMIC_NUM_CLASSES = 2
MIMIC_MAX_LENGTH = 48

PEMSBAY_NUM_FEATURES = 15
PEMSBAY_MAX_LENGTH = 24